### ISSUE TITLE
ISBAT install dependencies with npm install 

### ISSUE THREAD

**Issue by g4floyd** [johnjoseph3/sequencer#1] opened 2017-01-14 20:06 UTC
On fresh clone of forked repo, running `npm install` results in 
`npm WARN drum-machine@1.0.0 No repository field.` after branch diagram of dependencies. 
node_modules folder appears to include folders and files for the list of dependencies. 

When running `npm run start-dev` I receive this error: 

username$ npm run start-dev

> drum-machine@1.0.0 start-dev /Users/garymeyer/web-dev/sequencer
> webpack-dev-server --content-base dist/ --inline

sh: webpack-dev-server: command not found

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-dev"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! drum-machine@1.0.0 start-dev: `webpack-dev-server --content-base dist/ --inline`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the drum-machine@1.0.0 start-dev script 'webpack-dev-server --content-base dist/ --inline'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the drum-machine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --content-base dist/ --inline
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs drum-machine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls drum-machine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/garymeyer/web-dev/sequencer/npm-debug.log

**Comment by johnjoseph3** [comment] 2017-01-14 21:18
This was caused by webpack-dev-server being absent from the package.json file. The issue was resolved by adding webpack-dev-server to dev dependencies.

**Closed as completed** 2017-01-14 21:18 UTC
